import {
  ArrowLeftRightIcon,
  ArrowLeft01Icon,
  BellIcon,
  Cancel01Icon,
  CheckIcon,
  CircleIcon,
  ClipboardListIcon,
  Delete01Icon,
  Edit01Icon,
  EyeIcon,
  EyeOffIcon,
  GripVerticalIcon,
  HandCoinsIcon,
  Loading03Icon,
  Logout01Icon,
  MoreHorizontalIcon,
  Package01Icon,
  PlusSignIcon,
  ReloadIcon,
  Search01Icon,
  Settings01Icon,
  Settings02Icon,
  Store01Icon,
  TruckIcon,
  UnfoldMoreIcon,
  UserGroupIcon,
  ViewSidebarLeftIcon,
  WarehouseIcon,
  ArrowDown01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Xls01Icon,
} from '@hugeicons/core-free-icons'
import {
  ArrowLeft,
  ArrowLeftRight,
  Bell,
  CheckIcon as LucideCheck,
  ChevronDownIcon,
  ChevronRight,
  ChevronUpIcon,
  ChevronsUpDown,
  CircleIcon as LucideCircle,
  ClipboardList,
  Eye,
  EyeOff,
  FileSpreadsheet,
  GripVertical,
  HandCoins,
  Loader2,
  LogOut,
  MoreHorizontal,
  Package,
  PanelLeftIcon,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Settings2,
  Store,
  Trash2,
  Truck,
  Users,
  Warehouse,
  XIcon,
} from 'lucide-react'
import {
  ArrowLeft as PhArrowLeft,
  ArrowsLeftRight,
  Bell as PhBell,
  CaretDown,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Check,
  Circle,
  ClipboardText,
  Eye as PhEye,
  EyeSlash,
  DotsSixVertical,
  FileXls,
  Gear,
  GearSix,
  HandCoins as PhHandCoins,
  MagnifyingGlass,
  Package as PhPackage,
  PencilSimple,
  Plus as PhPlus,
  Sidebar,
  SignOut,
  Storefront,
  Trash,
  Truck as PhTruck,
  Users as PhUsers,
  Warehouse as PhWarehouse,
  X,
  CircleNotch,
  ArrowCounterClockwise,
  DotsThree,
} from '@phosphor-icons/react'
import {
  RiAddLine,
  RiArrowLeftLine,
  RiArrowDownSLine,
  RiArrowLeftRightLine,
  RiArrowRightSLine,
  RiArrowUpSLine,
  RiBellLine,
  RiBox3Line,
  RiBuilding4Line,
  RiCheckLine,
  RiCircleLine,
  RiClipboardLine,
  RiCloseLine,
  RiDeleteBinLine,
  RiDragMove2Line,
  RiExpandUpDownLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFileExcel2Line,
  RiGroupLine,
  RiHandCoinLine,
  RiLayoutLeftLine,
  RiLoader4Line,
  RiLogoutBoxRLine,
  RiMoreLine,
  RiPencilLine,
  RiRefreshLine,
  RiSearchLine,
  RiSettings2Line,
  RiSettingsLine,
  RiStore2Line,
  RiTruckLine,
} from '@remixicon/react'
import {
  IconArrowLeft,
  IconArrowsLeftRight,
  IconBell,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconClipboardList,
  IconCoins,
  IconDots,
  IconEye,
  IconEyeOff,
  IconFileExcel,
  IconGripVertical,
  IconLayoutSidebar,
  IconLoader2,
  IconLogout,
  IconPackage,
  IconPencil,
  IconPlus,
  IconRotate,
  IconSearch,
  IconSelector,
  IconSettings,
  IconSettings2,
  IconTrash,
  IconTruck,
  IconUsers,
  IconX,
} from '@tabler/icons-react'

import { asIcon, hugeicon, phosphorIcon, remixIcon } from '@/components/icons/icon-helpers'
import type { AppIconName, IconComponent, IconRegistry, IconRegistryMap } from '@/components/icons/icon.types'

const lucideRegistry: IconRegistry = {
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  bell: Bell,
  check: LucideCheck,
  'chevron-down': ChevronDownIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  circle: LucideCircle,
  'clipboard-list': ClipboardList,
  eye: Eye,
  'eye-off': EyeOff,
  excel: FileSpreadsheet,
  'grip-vertical': GripVertical,
  'hand-coins': HandCoins,
  loader: Loader2,
  'log-out': LogOut,
  'more-horizontal': MoreHorizontal,
  package: Package,
  'panel-left': PanelLeftIcon,
  pencil: Pencil,
  plus: Plus,
  'rotate-ccw': RotateCcw,
  search: Search,
  settings: Settings,
  'settings-2': Settings2,
  store: Store,
  'trash-2': Trash2,
  truck: Truck,
  users: Users,
  warehouse: Warehouse,
  x: XIcon,
}

const tablerRegistry: IconRegistry = {
  'arrow-left': asIcon(IconArrowLeft),
  'arrow-left-right': asIcon(IconArrowsLeftRight),
  bell: asIcon(IconBell),
  check: asIcon(IconCheck),
  'chevron-down': asIcon(IconChevronDown),
  'chevron-up': asIcon(IconChevronUp),
  'chevron-right': asIcon(IconChevronRight),
  'chevrons-up-down': asIcon(IconSelector),
  circle: asIcon(IconCircle),
  'clipboard-list': asIcon(IconClipboardList),
  eye: asIcon(IconEye),
  'eye-off': asIcon(IconEyeOff),
  excel: asIcon(IconFileExcel),
  'grip-vertical': asIcon(IconGripVertical),
  'hand-coins': asIcon(IconCoins),
  loader: asIcon(IconLoader2),
  'log-out': asIcon(IconLogout),
  'more-horizontal': asIcon(IconDots),
  package: asIcon(IconPackage),
  'panel-left': asIcon(IconLayoutSidebar),
  pencil: asIcon(IconPencil),
  plus: asIcon(IconPlus),
  'rotate-ccw': asIcon(IconRotate),
  search: asIcon(IconSearch),
  settings: asIcon(IconSettings),
  'settings-2': asIcon(IconSettings2),
  store: asIcon(IconBuildingStore),
  'trash-2': asIcon(IconTrash),
  truck: asIcon(IconTruck),
  users: asIcon(IconUsers),
  warehouse: asIcon(IconBuildingWarehouse),
  x: asIcon(IconX),
}

const phosphorRegistry: IconRegistry = {
  'arrow-left': phosphorIcon(PhArrowLeft, 'ArrowLeft'),
  'arrow-left-right': phosphorIcon(ArrowsLeftRight, 'ArrowsLeftRight'),
  bell: phosphorIcon(PhBell, 'Bell'),
  check: phosphorIcon(Check, 'Check'),
  'chevron-down': phosphorIcon(CaretDown, 'CaretDown'),
  'chevron-up': phosphorIcon(CaretUp, 'CaretUp'),
  'chevron-right': phosphorIcon(CaretRight, 'CaretRight'),
  'chevrons-up-down': phosphorIcon(CaretUpDown, 'CaretUpDown'),
  circle: phosphorIcon(Circle, 'Circle'),
  'clipboard-list': phosphorIcon(ClipboardText, 'ClipboardText'),
  eye: phosphorIcon(PhEye, 'Eye'),
  'eye-off': phosphorIcon(EyeSlash, 'EyeSlash'),
  excel: phosphorIcon(FileXls, 'FileXls'),
  'grip-vertical': phosphorIcon(DotsSixVertical, 'DotsSixVertical'),
  'hand-coins': phosphorIcon(PhHandCoins, 'HandCoins'),
  loader: phosphorIcon(CircleNotch, 'CircleNotch'),
  'log-out': phosphorIcon(SignOut, 'SignOut'),
  'more-horizontal': phosphorIcon(DotsThree, 'DotsThree'),
  package: phosphorIcon(PhPackage, 'Package'),
  'panel-left': phosphorIcon(Sidebar, 'Sidebar'),
  pencil: phosphorIcon(PencilSimple, 'PencilSimple'),
  plus: phosphorIcon(PhPlus, 'Plus'),
  'rotate-ccw': phosphorIcon(ArrowCounterClockwise, 'ArrowCounterClockwise'),
  search: phosphorIcon(MagnifyingGlass, 'MagnifyingGlass'),
  settings: phosphorIcon(Gear, 'Gear'),
  'settings-2': phosphorIcon(GearSix, 'GearSix'),
  store: phosphorIcon(Storefront, 'Storefront'),
  'trash-2': phosphorIcon(Trash, 'Trash'),
  truck: phosphorIcon(PhTruck, 'Truck'),
  users: phosphorIcon(PhUsers, 'Users'),
  warehouse: phosphorIcon(PhWarehouse, 'Warehouse'),
  x: phosphorIcon(X, 'X'),
}

const remixRegistry: IconRegistry = {
  'arrow-left': remixIcon(RiArrowLeftLine, 'RiArrowLeftLine'),
  'arrow-left-right': remixIcon(RiArrowLeftRightLine, 'RiArrowLeftRightLine'),
  bell: remixIcon(RiBellLine, 'RiBellLine'),
  check: remixIcon(RiCheckLine, 'RiCheckLine'),
  'chevron-down': remixIcon(RiArrowDownSLine, 'RiArrowDownSLine'),
  'chevron-up': remixIcon(RiArrowUpSLine, 'RiArrowUpSLine'),
  'chevron-right': remixIcon(RiArrowRightSLine, 'RiArrowRightSLine'),
  'chevrons-up-down': remixIcon(RiExpandUpDownLine, 'RiExpandUpDownLine'),
  circle: remixIcon(RiCircleLine, 'RiCircleLine'),
  'clipboard-list': remixIcon(RiClipboardLine, 'RiClipboardLine'),
  eye: remixIcon(RiEyeLine, 'RiEyeLine'),
  'eye-off': remixIcon(RiEyeOffLine, 'RiEyeOffLine'),
  excel: remixIcon(RiFileExcel2Line, 'RiFileExcel2Line'),
  'grip-vertical': remixIcon(RiDragMove2Line, 'RiDragMove2Line'),
  'hand-coins': remixIcon(RiHandCoinLine, 'RiHandCoinLine'),
  loader: remixIcon(RiLoader4Line, 'RiLoader4Line'),
  'log-out': remixIcon(RiLogoutBoxRLine, 'RiLogoutBoxRLine'),
  'more-horizontal': remixIcon(RiMoreLine, 'RiMoreLine'),
  package: remixIcon(RiBox3Line, 'RiBox3Line'),
  'panel-left': remixIcon(RiLayoutLeftLine, 'RiLayoutLeftLine'),
  pencil: remixIcon(RiPencilLine, 'RiPencilLine'),
  plus: remixIcon(RiAddLine, 'RiAddLine'),
  'rotate-ccw': remixIcon(RiRefreshLine, 'RiRefreshLine'),
  search: remixIcon(RiSearchLine, 'RiSearchLine'),
  settings: remixIcon(RiSettingsLine, 'RiSettingsLine'),
  'settings-2': remixIcon(RiSettings2Line, 'RiSettings2Line'),
  store: remixIcon(RiStore2Line, 'RiStore2Line'),
  'trash-2': remixIcon(RiDeleteBinLine, 'RiDeleteBinLine'),
  truck: remixIcon(RiTruckLine, 'RiTruckLine'),
  users: remixIcon(RiGroupLine, 'RiGroupLine'),
  warehouse: remixIcon(RiBuilding4Line, 'RiBuilding4Line'),
  x: remixIcon(RiCloseLine, 'RiCloseLine'),
}

const hugeiconsRegistry: IconRegistry = {
  'arrow-left': hugeicon(ArrowLeft01Icon, 'ArrowLeft'),
  'arrow-left-right': hugeicon(ArrowLeftRightIcon, 'ArrowLeftRight'),
  bell: hugeicon(BellIcon, 'Bell'),
  check: hugeicon(CheckIcon, 'Check'),
  'chevron-down': hugeicon(ArrowDown01Icon, 'ArrowDown'),
  'chevron-up': hugeicon(ArrowUp01Icon, 'ArrowUp'),
  'chevron-right': hugeicon(ArrowRight01Icon, 'ArrowRight'),
  'chevrons-up-down': hugeicon(UnfoldMoreIcon, 'UnfoldMore'),
  circle: hugeicon(CircleIcon, 'Circle'),
  'clipboard-list': hugeicon(ClipboardListIcon, 'ClipboardList'),
  eye: hugeicon(EyeIcon, 'Eye'),
  'eye-off': hugeicon(EyeOffIcon, 'EyeOff'),
  excel: hugeicon(Xls01Icon, 'Xls'),
  'grip-vertical': hugeicon(GripVerticalIcon, 'GripVertical'),
  'hand-coins': hugeicon(HandCoinsIcon, 'HandCoins'),
  loader: hugeicon(Loading03Icon, 'Loading'),
  'log-out': hugeicon(Logout01Icon, 'Logout'),
  'more-horizontal': hugeicon(MoreHorizontalIcon, 'MoreHorizontal'),
  package: hugeicon(Package01Icon, 'Package'),
  'panel-left': hugeicon(ViewSidebarLeftIcon, 'ViewSidebarLeft'),
  pencil: hugeicon(Edit01Icon, 'Edit'),
  plus: hugeicon(PlusSignIcon, 'Plus'),
  'rotate-ccw': hugeicon(ReloadIcon, 'Reload'),
  search: hugeicon(Search01Icon, 'Search'),
  settings: hugeicon(Settings01Icon, 'Settings'),
  'settings-2': hugeicon(Settings02Icon, 'Settings2'),
  store: hugeicon(Store01Icon, 'Store'),
  'trash-2': hugeicon(Delete01Icon, 'Delete'),
  truck: hugeicon(TruckIcon, 'Truck'),
  users: hugeicon(UserGroupIcon, 'UserGroup'),
  warehouse: hugeicon(WarehouseIcon, 'Warehouse'),
  x: hugeicon(Cancel01Icon, 'Cancel'),
}

export const ICON_REGISTRIES: IconRegistryMap = {
  lucide: lucideRegistry,
  tabler: tablerRegistry,
  hugeicons: hugeiconsRegistry,
  phosphor: phosphorRegistry,
  remix: remixRegistry,
}

export function getIconComponent(
  library: keyof IconRegistryMap,
  name: AppIconName,
): IconComponent {
  return ICON_REGISTRIES[library][name] ?? ICON_REGISTRIES.lucide[name]
}
